### ISSUE TITLE
Check for owner of the api key

### ISSUE THREAD

**Issue by NT-Thanh** [mihirdilip/aspnetcore-authentication-apikey#11]
I wonder how can i check that a owner are using an api key that belongs to another client and prevent it?
Is there any way to pass owner name within the header and then validate it in the ProvideAsync method

**Comment by mihirdilip** [comment]
@NT-Thanh not sure if I understand your question. Can you give me a scenario of what you are trying to solve here?

Assuming you are using aspnetcore, you should be able to access any request headers you want in the ProvideAsync method by injecting IHttpContextAccessor via constructor to the implementation of IApiKeyProvider. Please refer to this link on how to use it.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.1#use-httpcontext-from-custom-components

**Comment by mihirdilip** [comment]
@NT-Thanh did you manage to solve your problem?

**Comment by NT-Thanh** [comment]
> @NT-Thanh not sure if I understand your question. Can you give me a scenario of what you are trying to solve here?
> 
> Assuming you are using aspnetcore, you should be able to access any request headers you want in the ProvideAsync method by injecting IHttpContextAccessor via constructor to the implementation of IApiKeyProvider. Please refer to this link on how to use it.
> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.1#use-httpcontext-from-custom-components

This's exactly what i need, thank you so much!
