### ISSUE TITLE
Incorrect Handler being applied in AddApiKeyInHeader

### ISSUE THREAD

**Issue by maartenmensink** [mihirdilip/aspnetcore-authentication-apikey#13]
Found a small bug in the extension. The extension implies only header handling should be applied but the ApiKeyInHeaderOrQueryParamsHandler is applied

On line https://github.com/mihirdilip/aspnetcore-authentication-apikey/blob/master/src/AspNetCore.Authentication.ApiKey/ApiKeyExtensions.cs#L130 it should be `ApiKeyInHeaderHandler` instead of `ApiKeyInHeaderOrQueryParamsHandler`

``` C#
public static AuthenticationBuilder AddApiKeyInHeader<TApiKeyProvider>(this AuthenticationBuilder builder, string authenticationScheme, string displayName, Action<ApiKeyOptions> configureOptions) where TApiKeyProvider : class, IApiKeyProvider
			=> builder.AddApiKey<TApiKeyProvider, ApiKeyInHeaderOrQueryParamsHandler>(authenticationScheme, displayName, configureOptions);
```

**Comment by mihirdilip** [comment]
Thanks for spotting this. I have pushed a fix with #14. I will soon push a new NuGet release.

**Comment by mihirdilip** [comment]
I have just spotted that there are some redundant extensions methods which I will get rid off in a bit. Once again thanks for your feedback, much appreciated.

**Comment by mihirdilip** [comment]
On second thought, I will leave them in just in case it is used/setup differently which I am not aware of. By the way I was thinking of removing the extension methods without configureOptions parameter as some properties on this options are required to be set. And now I have decided not to.

```C#
public static AuthenticationBuilder AddApiKeyInHeader(this AuthenticationBuilder builder)
    => builder.AddApiKeyInHeader(ApiKeyDefaults.AuthenticationScheme);
```
