### ISSUE TITLE
Identity IsAuthenticated false

### ISSUE THREAD

**Issue by ZNS** [mihirdilip/aspnetcore-authentication-apikey#17]
Hi. I've tried to implement this. The ApiKeyProvider triggers and returns a IApiKey and it seems to work but HttpContext.User.Identity.IsAuthenticated is still false. Do I need to implement this myself like calling HttpContext.SignInAsync?

**Comment by ZNS** [comment]
My bad I guess. I returned an empty claims list, when I added a claim it seems to work.

**Comment by mihirdilip** [comment]
Hi @ZNS, Not sure how you are using the library and which version? I have tried with empty claims list from the Provider and it works fine. Please send some code snippet if you are still having problem otherwise please close the issue.
