### ISSUE TITLE
Error ApiKeyInHeaderOrQueryParamsHandler

### ISSUE THREAD

**Issue by tranthaibinh111** [mihirdilip/aspnetcore-authentication-apikey#19]
Hi @mihirdilip ,
Now, I used version 5.0.0.

I have some APIs that allow anonymously. I set ApiKeyOptions.IgnoreAuthenticationIfAllowAnonymous to true on Startup.cs.
However, I was been an error "Invalid API Key provided by IApiKeyProvider" at 
AspNetCore.Authentication.ApiKey.ApiKeyInHeaderOrQueryParamsHandler  when running.

Please help me. ^_^

**Comment by mihirdilip** [comment]
Hi @tranthaibinh111 please send me the code snippet of your startup class, problem controller/endpoint and ApiKeyProvider and also what aspnetcore version you are using? Or may be point me to you GitHub repo where you are using this.

**Comment by tranthaibinh111** [comment]
Hi @mihirdilip, 

I was using .NET Core 3.1.10 and deployed on IIS 10.

Startup.cs
-------------------------------------------------------------------------------
public void ConfigureServices(IServiceCollection services)
{
  #region Security
  services.AddCors(options =>
    options.AddPolicy(MyAllowSpecificOrigins,
      builder =>
      {
        // Origins
        var origins = new List<string> { "***.com" };

        if (CurrentEnvironment.IsDevelopment())
          origins.AddRange(new List<string> {
            "http://***.com",
            "http://localhost:5000",
          });

        builder.WithOrigins(origins.ToArray());
        // Header
        builder.WithHeaders(HeaderNames.ContentType);
        // Methods
        builder.WithMethods("GET", "POST", "PUT", "PATCH");
      }
    )
  );

  // https://github.com/mihirdilip/aspnetcore-authentication-apikey#startupcs-aspnet-core-30-or-newer
  // Add the API Key authentication here..
  // AddApiKeyInHeaderOrQueryParams extension takes an implementation of IApiKeyProvider for validating the key.
  // It also requires Realm and KeyName to be set in the options.
  services.AddAuthentication(ApiKeyDefaults.AuthenticationScheme)
    //// use below to accept API Key either in header or query parameter
    .AddApiKeyInHeaderOrQueryParams<ApiKeyProvider>(options =>
    {
      options.Realm = "ANN Shop";
      options.KeyName = "Authorization";  // Your api key name which the clients will require to send the key.
      options.IgnoreAuthenticationIfAllowAnonymous = true;
      options.ForLegacyIgnoreExtraValidatedApiKeyCheck = true;
    });

  services.AddResponseCompression(options =>
  {
    options.Providers.Add<BrotliCompressionProvider>();
    options.Providers.Add<GzipCompressionProvider>();
    options.MimeTypes =
      ResponseCompressionDefaults.MimeTypes.Concat(
        new[] { "image/svg+xml" });
  });
  #endregion

  #region Response Caching Middleware
  services.AddResponseCaching(options =>
  {
    options.MaximumBodySize = 1024;
    options.UseCaseSensitivePaths = true;
  });
  #endregion

  #region DBContext
  services.AddDbContext<ANNShopContext>(options => options
    .UseSqlServer(Configuration.GetConnectionString("***")), ServiceLifetime.Scoped);
  #endregion

  #region Provider
  services.AddScoped<IConfiguration>(provider => Configuration);
  services.AddHttpClient();
  #endregion

  #region Filters
  services.Configure<ApiBehaviorOptions>(options => options.SuppressModelStateInvalidFilter = true);
  #endregion

  #region Controllers
  services.AddControllers(options => options.Filters.Add(typeof(ValidateModelFilter)))
    .AddNewtonsoftJson(x => x.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore);
  #endregion
}

NotificationController.cs
-------------------------------------------------------------------------------
[Authorize]
[ApiController]
[ApiExplorerSettings(GroupName = "flutter-v1")]
[Produces("application/json")]
[Route("api/flutter/notification")]
public class NotificationController : ControllerBase
{
...
    AllowAnonymous]
    [HttpGet]
    [Route("~/api/flutter/home/notifications")]
    [ProducesResponseType(typeof(List<BannerResponseModel>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponseModel), StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> getHomeNotification()
    {
      try
      {
        var notifications = await _service.getHomeNotification();

        return Ok(notifications);
      }
      catch (Exception ex)
      {
        _logger.LogError(ex, ex.Message);
        var response = new ErrorResponseModel("***");

        return StatusCode(StatusCodes.Status500InternalServerError, response);
      }
    }
}

Please help me. ^_^

**Comment by mihirdilip** [comment]
Hi @tranthaibinh111 thanks for sending the code snippets. 
- I tried it myself on my sample app with AllowAnonymous on one of the endpoint on controller and similar settings as yours on startup AddApiKeyInHeaderOrQueryParams which worked for me without any issue. So I was not able to replicate the issue.
- I still need to see Configure method on the Startup class to see how you are setting up the middlewares pipeline. So, it would be best if you send your whole startup class (with secrets removed).
- I have noticed that you are neither using an implementation of IApiKeyProvider with options.AddApiKeyInHeaderOrQueryParams<???>() nor setting up options.Events.OnValidateKey.
    - It will need either of the above setting to be able to work otherwise it throws an error when starting the application.
- I noticed you are using *options.KeyName = "Authorization"*. Are you trying to use the authorization header with Basic or Bearer or your own scheme name? 
    - This library also checks Authorization header where above KeyName is the scheme part and value part is the secret key. So if you set the *options.KeyName="Basic"* then it looks for Basic scheme in Authorization header and uses value part as the the-secret-key i.e. ```curl https://localhost/xyz -H "Authorization: Basic the-secret-key"```. And similarly if you set *options.KeyName="Bearer"* then it looks for Bearer scheme in Authorization header and uses value part as the-secret-access-token i.e. ```curl https://localhost/xyz -H "Authorization: Bearer the-secret-access-token"```. 
    - If you want to use basic authentication and unless you have not noticed it already then I have another library that might help [AspNetCore.Authentication.Basic](https://www.nuget.org/packages/AspNetCore.Authentication.Basic/)

**Comment by tranthaibinh111** [comment]
Hi @mihirdilip ,



> Hi @tranthaibinh111 thanks for sending the code snippets.
> 
> * I tried it myself on my sample app with AllowAnonymous on one of the endpoint on controller and similar settings as yours on startup AddApiKeyInHeaderOrQueryParams which worked for me without any issue. So I was not able to replicate the issue.
> * I still need to see Configure method on the Startup class to see how you are setting up the middlewares pipeline. So, it would be best if you send your whole startup class (with secrets removed).
> * I have noticed that you are neither using an implementation of IApiKeyProvider with options.AddApiKeyInHeaderOrQueryParams<???>() nor setting up options.Events.OnValidateKey.
>   
>   * It will need either of the above setting to be able to work otherwise it throws an error when starting the application.
> * I noticed you are using _options.KeyName = "Authorization"_. Are you trying to use the authorization header with Basic or Bearer or your own scheme name?
>   
>   * This library also checks Authorization header where above KeyName is the scheme part and value part is the secret key. So if you set the _options.KeyName="Basic"_ then it looks for Basic scheme in Authorization header and uses value part as the the-secret-key i.e. `curl https://localhost/xyz -H "Authorization: Basic the-secret-key"`. And similarly if you set _options.KeyName="Bearer"_ then it looks for Bearer scheme in Authorization header and uses value part as the-secret-access-token i.e. `curl https://localhost/xyz -H "Authorization: Bearer the-secret-access-token"`.
>   * If you want to use basic authentication and unless you have not noticed it already then I have another library that might help [AspNetCore.Authentication.Basic](https://www.nuget.org/packages/AspNetCore.Authentication.Basic/)

**Comment by tranthaibinh111** [comment]
Hello @mihirdilip!

1) I have set options.AddApiKeyInHeaderOrQueryParams<ApiKeyProvider>().
2) I'm glad I knew how to use the option.KeyName = "Authorize".
I hope you will write option.KeyName = "Authorize" in README.md.
3) Sometimes my SEQ logger reports a problem but my back-end works fine. In recent days, do not see the above problem. Hence I will close this issue. 

Thanks very much. ^ _ ^

**Comment by mihirdilip** [comment]
@tranthaibinh111 thanks for letting me know that it is working :)
