### ISSUE TITLE
ApikeyProvider never called

### ISSUE THREAD

**Issue by farlee2121** [mihirdilip/aspnetcore-authentication-apikey#2]
I'm trying to setup api authentication with Asp.Net Core 3.1. To the best of my ability to discern, i'm following this library's setup instructions, but I always get a 401 Unauthorized response without a call to my ApiKeyProvider.

Is the library perhaps not compatible with Asp.Net Core 3.1?

Here's what I've got so far

```cs
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            // doesn't make any difference if I add app.UseAuthentication() here
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseSwagger();
            app.UseSwaggerUI(config =>
            {
                config.SwaggerEndpoint("/swagger/v1/swagger.json", "FastFit");
            });
        }
``` 

```cs
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();


            services.AddAuthentication(ApiKeyDefaults.AuthenticationScheme).AddApiKeyInHeader<ApiKeyProvider>(options =>
            {
                options.Realm = "Profit";
                options.KeyName = "X-API-KEY";
            });
            services.AddSwaggerGen(config => {
                config.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
                config.AddSecurityDefinition(ApiKeyDefaults.AuthenticationScheme, new OpenApiSecurityScheme()
                {
                    In = ParameterLocation.Header, 
                    Name = "X-API-KEY", 
                    Type = SecuritySchemeType.ApiKey,
                });
            });

            
        }
```

```cs
    public class ApiKeyProvider : IApiKeyProvider
    {
        public Task<IApiKey> ProvideAsync(string key)
        {
            var config = new ConfigurationBuilder().Build();
            string expectedApiKey = //magic
            IApiKey validKeyClaim;
            if (!string.IsNullOrWhiteSpace(expectedApiKey) && key == expectedApiKey)
            {
                validKeyClaim = new ApiKey(key);
            }
            else
            {
                validKeyClaim = null;
            }
            return Task.FromResult<IApiKey>(validKeyClaim);
        }
    }
```

```cs
        [Authorize]
        [HttpPost]
        public IActionResult RequestRecommendation(FittingRequest fittingRequest)
        {
           //...
        }
```

**Comment by farlee2121** [comment]
Well, a few issues going on, but the key part was that `startup.cs` must __not__ call `app.UseAuthorization()`

**Comment by mihirdilip** [comment]
@farlee2121 thank you for your feedback. I really appreciate it. I have not tested it on Asp.Net Core 3.1 yet. Did you get it working? Usually the order should be app.UseAuthentication(); before app.UseAuthorization(); 

I would really appreciate if you can let me know of other issues so that I can address them and fix them.

**Comment by farlee2121** [comment]
I thought I had it working, but sadly I did not.

Once I removed .UseAuthorization(), it would hit my breakpoint in the ApiKeyProvider. However, then it would 500 error saying that there was no middleware to handle the Authorize attribute (makes sense).
I don't understand the NetCore auth pipeline well enough yet to have an intuition for the breakpoint behavior : /

It didn't matter what order I had UseAuthorization and UseAuthentication in, I tried both. 
I suppose I should try setting the asp.net compatibility version.

Is there anything you'd like me to try?

**Comment by mihirdilip** [comment]
Hi @farlee2121
Please bear with me as I am messaging from my phone.

You need to move UseSwagger bits to top. UseEndpoints should be last in the pipeline. Refer to this document..
https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle 

Also I have noticed in your sample you are building Configuration in the ProvideAsync() method. In case if you are not aware, you can dependency inject via constructor using IConfiguration interface. 

I completely forgot about the samples repository I had started. And it is working as expected. 

Please refer to my project on this repository which is developed for dotnetcore3.1
https://github.com/mihirdilip/authentication-serverside-samples

And to consume these server side projects I have another repository
https://github.com/mihirdilip/authentication-clientside-samples

Client side samples is using restful API client library which is still under development but you are more than welcome to have a go at it and let me know what you think about it. It is under development hence it is in preview on NuGet.

**Comment by mihirdilip** [comment]
Hi @farlee2121, Did you had any luck with the above?

**Comment by farlee2121** [comment]
I'm confused. I ran your sample app, it worked as expected. 
I tried implementing it in my project, wasn't working. Kept fiddling, and suddenly it worked. Now I can't get it to break again.

Something that may have been tripping me up, **the ApiKeyProvider will not be called if the expected apikey header is not present**.

 If I had to guess, I thought I was running tests with and without a header against different configurations but was really only making requests without the apikey header.

**Comment by farlee2121** [comment]
Thanks for your help!

**Comment by mihirdilip** [comment]
No worries.. Good to know that you have got it working.

**Comment by mihirdilip** [comment]
Hi @farlee2121, 

I hope you are well.

I apologize that I may have missunderstood your comment. I read it as you had got it working until I was pointed to this comment by above.

In case if you still have this issue outstanding.. try the following on ConfigureServices method on Startup class. 

```
services.AddControllers(options => { 
                options.Filters.Add(new AuthorizeFilter(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build()));
            });
```

**Comment by farlee2121** [comment]
Thanks for checking in.

The behavior mentioned in issue #3 is not the behavior I thought I was seeing before. However, I tested and was able to replicate the issue. I'd say that qualifies as a security flaw 😰

**Comment by mihirdilip** [comment]
I would not class it as security flaw. It is how asp.net core is designed. You have to opt in to authorize specific or all request(s) you want to authorize. 

To authorize a specific endpoint you can decorate either the controller or the method with [Authorize] (filter) attribute.

To apply authorize filter all the requests by default you have to add the following to the Startup class.

```
services.AddControllers(options => { 
                options.Filters.Add(new AuthorizeFilter(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build()));
            });
```

Please refer to
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-3.1

and 

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.1
