### ISSUE TITLE
Change visibility of ApiKeyInAuthorizationHeaderHandler

### ISSUE THREAD

**Issue by OPSnake** [mihirdilip/aspnetcore-authentication-apikey#21]
Change visibility of ApiKeyInAuthorizationHeaderHandler to public.

**Comment by mihirdilip** [comment]
Thanks for your comment @OPSnake. Some explanation/reason for doing so would help.

**Comment by OPSnake** [comment]
I dynamically configure and inject different authentication handlers into a multi-tenant application depending on the client configuration.

For that I would need to access the ApiKeyInAuthorizationHeaderHandler class rather than looking for it by relflection

**Comment by mihirdilip** [comment]
@OPSnake, please send a code snippet where/how you configure and inject different authentication handlers depending on configuration?

Would you be able to use IAuthenticationSchemeProvider to extract Handler type?

```C#
var schemeProvider = services.GetRequiredService<IAuthenticationSchemeProvider>();
Assert.NotNull(schemeProvider);
			
var scheme = await schemeProvider.GetDefaultAuthenticateSchemeAsync();
Assert.NotNull(scheme);
Assert.Equal(typeof(ApiKeyInAuthorizationHeaderHandler), scheme.HandlerType);
```

**Comment by mihirdilip** [comment]
Hi @OPSnake, just to let you know that I have changed the visibility of all the handlers to public with new release of the library.  
[Link to NuGet](https://www.nuget.org/packages/AspNetCore.Authentication.ApiKey/5.1.0)   
[Link to Release](https://github.com/mihirdilip/aspnetcore-authentication-apikey/releases/tag/5.1.0)

Thanks for using the library and your feedback.
