### ISSUE TITLE
CustomResponse on NotAuthorization

### ISSUE THREAD

**Issue by renerlemes** [mihirdilip/aspnetcore-authentication-apikey#24]
How to implement the custom data to return in the response when the status code is 401 Unauthorized in class that implement the IApiKeyProvider?

**Comment by mihirdilip** [comment]
@renerlemes, IApiKeyProvider is not responsible for such complex task. 

Why don't you set ApiKeyOptions.Events.OnHandleChallenge? Have a look at the Sample code below. It is commented out but that it how you can set anything you want on the response.
https://github.com/mihirdilip/aspnetcore-authentication-apikey/blob/bd929dc891d632d42e3c58bba595de49e067e89c/samples/SampleWebApi_5_0/Startup.cs#L114 

If you really want to try it on implementation of IApiKeyProvider which I have not tried it myself but you can give it a go if you want. Try using HttpContextAccessor to access HttpContext in IApiKeyProvider and set the context.Response to what you would like and see if it works or not. Once again I have not tried it myself.

I hope the above helps..

**Comment by mihirdilip** [comment]
I had a quick go on my sample project mentioned above and it actually works as long as ProvideAsync method is hit!

```C#
	class ApiKeyProvider : IApiKeyProvider
	{
		private readonly ILogger<IApiKeyProvider> _logger;
		private readonly IApiKeyRepository _apiKeyRepository;
		private readonly IHttpContextAccessor _httpContextAccessor;

		public ApiKeyProvider(ILogger<IApiKeyProvider> logger, IApiKeyRepository apiKeyRepository, IHttpContextAccessor httpContextAccessor)
		{
			_logger = logger;
			_apiKeyRepository = apiKeyRepository;
			_httpContextAccessor = httpContextAccessor;
		}

		public async Task<IApiKey> ProvideAsync(string key)
		{
			try
			{
				await _httpContextAccessor.HttpContext.Response.WriteAsync("My Custom Response!");

				return await _apiKeyRepository.GetApiKeyAsync(key);
			}
			catch (System.Exception exception)
			{
				_logger.LogError(exception, exception.Message);
				throw;
			}
		}
	}
```

**Comment by renerlemes** [comment]
In the other issue I sent you, I did this example using the IApiKeyProvider implementation and it worked. I used the Events that would be in Startup.cs within the class. I don't know if it's the best way to do it, but it worked.
But if you have any suggestions, if not, you can close this issue.

**Comment by mihirdilip** [comment]
@renerlemes, it is perfectly correct way to do it. My suggestion is to override `ValidateKeyAsync(ApiKeyValidateKeyContext context)` method from ApiKeyEvents and remove implementation of `IApiKeyProvider`. Please see [my comment](https://github.com/mihirdilip/aspnetcore-authentication-apikey/issues/23#issuecomment-791930334) on your other issue #23.

**Comment by renerlemes** [comment]
I lost the project that had the implementation of this question working. That's why I'm reopening.

I'm using ApiKeyEvents and when it's not valid for example the key, I use context.ValidationFailed() and it's still allowing to enter the controller, shouldn't it return 401? The HandleChallengeAsync method is not called too.

**Comment by mihirdilip** [comment]
Please send me your code implementation ApiKeyEvents.

**Comment by renerlemes** [comment]
I found the problem. I´m using the custom Authorize Filter. 
So after ValidateKeyAsync method is ended, the custom authorize filter is called and return the Ok status per exemple and the method HandleChallengeAsync is not called. When I use Authorize filter only, it´s work.
Is possible to use with custom Authrorize Filter?

```
public class ApiKeyProvider : ApiKeyEvents
  {
      public ApiKeyProvider()
      {
          OnValidateKey = ValidateKeyAsync;
      }

      public async override Task ValidateKeyAsync(ApiKeyValidateKeyContext context)
      {
          var isValid = context.ApiKey != null && context.ApiKey.Equals("123456", StringComparison.OrdinalIgnoreCase);

          if (isValid)
          {
              ApiKey apiKey = new ApiKey(context.ApiKey, "Vamos Alugar");

              context.ValidationSucceeded(apiKey.OwnerName);

              context.HttpContext.Features.Set<IApiKey>(apiKey);
          }
          else
          {
              context.ValidationFailed();
          }
      }

      public async override Task HandleChallengeAsync(ApiKeyHandleChallengeContext context)
      {
          context.Response.StatusCode = StatusCodes.Status401Unauthorized;

          await context.Response.WriteAsync("{\"CustomBody\":\"From OnHandleChallenge\"}");

          context.Handled();
      }
  }
```

AuthorizeFilter.cs

```
public class AuthorizationFilter : IAuthorizationFilter
    {
        private readonly bool _VerificarPlano;

        public AuthorizationFilter(bool verificarPlano)
        {
            _VerificarPlano = verificarPlano;
        }

        public void OnAuthorization(AuthorizationFilterContext context)
        {
            //I think put here, validation to check if StatusCode is 401 and in HandleChallengeAsync  I set response.StatusCode = 401. What do you think?
            bool autorizado = true;

            if (!autorizado)
                context.Result = new StatusCodeResult(401);
        }

        
    }
```

See the comment in the OnAuthorization method

**Comment by mihirdilip** [comment]
That's right, your custom AuthorizationFilter is overriding the default authorization behaviour and, should validate and the set the context result as required. You could try what you suggested in the comments above if it works for you. The other option I can think of is to inherit from the default AuthorizeFilter?

Also, what are you trying to achieve by using custom Authorization filter? Can it not be solved by using Policy or something instead of having a custom authorize filter?

**Comment by renerlemes** [comment]
Inherit from AuthorizeFilter worked!
I create a custom Authorization Filter beacuse I wanted a custom parameters instead use Policy.
Tks
