### ISSUE TITLE
How to add API key authorization so it is not required to APIs with other schemes?

### ISSUE THREAD

**Issue by veikkoeeva** [mihirdilip/aspnetcore-authentication-apikey#26]
Say, if I have the following setup with some controllers that are either with `[Authorize("AzureAd")]` or `[Authorize("ApiKeyScheme")]`. The intention is to require API key only for controllers marked with `[Authorize("ApiKeyScheme")]`.

It appears API calls fault also on  `[Authorize("AzureAd")]` since API key has not be sent. So it appears the API key is applied to all controllers with `[Authorize]` while (my) intention is only the controllers that are marked with `[Authorize("ApiKeyScheme")]`. 

What could be the way to apply API key requirement only to some select endpoints and not all with `Authorize` attribute?

In the following is the authentication and authorization pipelin on relevant parts, I think.

```
.AddJwtBearer("AzureAD", options =>
{
    options.Audience = Configuration["AzureAD:Audience"];
    options.Authority = Configuration["AzureAD:Authority"];
})
.AddApiKeyInHeader<ApiKeyProvider>("ApiKeyScheme", options =>
{
    options.Realm = "Just some example realm";
    options.KeyName = "x-api-key";
});

services.AddAuthorization(options =>
{
    var defaultAuthorizationPolicyBuilder = new AuthorizationPolicyBuilder(JwtBearerDefaults.AuthenticationScheme, "AzureAD");
    defaultAuthorizationPolicyBuilder = defaultAuthorizationPolicyBuilder.RequireAuthenticatedUser();
    options.DefaultPolicy = defaultAuthorizationPolicyBuilder.Build();
});

services.AddAuthorization(options =>
{
    var apiKeyAuthorization = new AuthorizationPolicyBuilder("ApiKeyScheme");
    apiKeyAuthorization = apiKeyAuthorization.RequireAuthenticatedUser();
    apiKeyAuthorization.RequireClaim(ApiKeyConstants.RequiredApiKeyClaim);
    options.DefaultPolicy = apiKeyAuthorization.Build();
});
```

This may be the wrong place to ask, so apologies for it. It occurred to me this could be of interest to potential users of this library.

**Comment by mihirdilip** [comment]
@veikkoeeva, You can remove both `AddAuthorization()` calls from your setup since you are decorating the specific controllers/endpoints with `[Authorize("SCHEME")]` metadata. 

Also, you should only have 1 AddAuthorization call to set DefaultPolicy. In your case, the last AddAuthorization sets DefaultPolicy to ApiKeyScheme and so it will always be triggered for all the calls no matter what is set on the controller/endpoint.

My recommendation, if you are decorating the specific controllers/endpoints with `[Authorize("SCHEME")]` metadata then remove `AddAuthorization()` calls and try if solves your problem.

If you want some fallback authentication for everything where you do not have any `[Authorize("SCHEME")]` metadata set on controller/endpoint, you can set `options.FallbackPolicy` instead of `options.DefaultPolicy` on `AddAuthorization()`.

**Comment by veikkoeeva** [comment]
@mihirdilip I can confirm your suggestion to remove `.AddAuthorization` and rely only on attributes on controllers does work. After this change API key is only required on controllers that are explicitly decorated with `[Authorize("ApiKeyScheme")]`.

This change presents two other things worth mentioning here, I believe. Going this route removes `RequireClaim(ApiKeyConstants.RequiredApiKeyClaim);` from the pipeline. It is maybe worth thinking if there is something in the API key handling one wants to and check like this (in my case not).

Anothr maybe is that if `[Authorize]` require authentication by default? Since removing it removes the call to `.RequireAuthenticatedUser();` for these two schemes (and API key) here. It is probably related to a question if `app.UseAuthorization();` is specifically required if it was not used before. It lools like not, but worth checking.

I tried in fact look for information on these authentication facts, but thought then to write back now since you were so prompt.

**Comment by veikkoeeva** [comment]
I dug a bit deeper into this. This interplay with authentication and authorization may be relavant to others who use `Authorize` attributes in different roles combined with authentication. A few links: https://github.com/dotnet/aspnetcore/issues/18954#issuecomment-624888077 and https://github.com/dotnet/AspNetCore.Docs/issues/16389.

**Comment by mihirdilip** [comment]
> @mihirdilip I can confirm your suggestion to remove `.AddAuthorization` and rely only on attributes on controllers does work. After this change API key is only required on controllers that are explicitly decorated with `[Authorize("ApiKeyScheme")]`.

Glad to know that it works for you.



> This change presents two other things worth mentioning here, I believe. Going this route removes `RequireClaim(ApiKeyConstants.RequiredApiKeyClaim);` from the pipeline. It is maybe worth thinking if there is something in the API key handling one wants to and check like this (in my case not).

Not sure if I understand your query, but I will try to answer.. 

You should be able to check this on the implementation of `IApiKeyProvider`? If you are not using `IApiKeyProvider` then it could be handled in `ApiKeyOptions.Events.OnValidateKey`?

Other way is to define Policy on your Startup class which you can use with `[Authorize("POLICY_NAME")]`?  [Check it out here..](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-5.0)

   
> Anothr maybe is that if `[Authorize]` require authentication by default? Since removing it removes the call to `.RequireAuthenticatedUser();` for these two schemes (and API key) here. It is probably related to a question if `app.UseAuthorization();` is specifically required if it was not used before. It lools like not, but worth checking.

Cannot understand clearly what you are asking here.. 
You will need `app.UseAuthorization();` on the pipeline to trigger authentication and authorization.

`[Authorize]` (without scheme name) will use the default scheme setup `services.AddAuthentication("DEFAULT SCHEME")`

If no DefaultPolicy is set and no `[Authorize]` attribute is used on the controller then it will not trigger any authentication.

If FallbackPolicy is set and no `[Authorize]` attribute is used on the controller then it will trigger the fallback policy.

I hope the above answers your question. I am afraid I was not able to understand your questions so I have tried to answer what I can really.

**Comment by veikkoeeva** [comment]
@mihirdilip I need to take that a bit back. The API key check does not need to succeed with that fix. I.e. the function

```
public Task<IApiKey> ProvideAsync(string key)
{
    try
    {
        var claims = new List<Claim>();
	if(string.Equals(key, "SomeApiKey", StringComparison.InvariantCulture))
	{
   	    claims.Add(new Claim(ApiKeyConstants.RequiredApiKeyClaim, string.Empty));
	}

	return Task.FromResult<IApiKey>(new ApiKey(key, ApiKeyConstants.KeyOwner, claims));
}
catch(Exception exception)
{
	Logger.LogError(exception, exception.Message);
	throw;
}
```

can set the claim or not but the end result is the same: no effect. I.e. the key can be whatever. This seems natural since there is nothing to check if there are claims.

EDIT: I just read better your message a few minutes before. Let I try to check the existence of a claim in handler.

**Comment by mihirdilip** [comment]
@veikkoeeva you can either use [something like this](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-5.0) if you want to Authorized based on claims.

Other trick is to add your claim as Roles and use `[Authorize("ApiKeyScheme", Roles = ApiKeyConstants.RequiredApiKeyClaim)]` ;)
Check out this line `claims.Add(new Claim(ClaimTypes.Roles, ApiKeyConstants.RequiredApiKeyClaim));` below.

```
public Task<IApiKey> ProvideAsync(string key)
{
    try
    {
        var claims = new List<Claim>();
	if(string.Equals(key, "SomeApiKey", StringComparison.InvariantCulture))
	{
   	    claims.Add(new Claim(ClaimTypes.Roles, ApiKeyConstants.RequiredApiKeyClaim));
	}

	return Task.FromResult<IApiKey>(new ApiKey(key, ApiKeyConstants.KeyOwner, claims));
}
catch(Exception exception)
{
	Logger.LogError(exception, exception.Message);
	throw;
}
```

**Comment by veikkoeeva** [comment]
@mihirdilip Heh, yes well, that adding `Roles` may bring new complications into picture as in one of the links is being discussed. :P 

I'll add here that the following seem to work. I think with this the issue can be closed. If I notice something I may try to test your kindness with a new one. Let I wish you a good day and thank you for the help!
```
.AddApiKeyInHeader<ApiKeyProvider>(ApiKeyConstants.SchemeName, options =>
            {                
                options.KeyName = "key-header";
                options.Events = new ApiKeyEvents
                {
                    OnValidateKey = async context =>
                    {
                        if(context.ApiKey != null && string.Equals(context.ApiKey, "SomeApiKey", StringComparison.InvariantCulture))
                        {
                           //Could add claims here...
                            context.ValidationSucceeded(null);
                        }
                        else
                        {
                            context.ValidationFailed();
                        }
                    }
                };
            });
```

**Comment by mihirdilip** [comment]
You are welcome @veikkoeeva. Thanks using the library for your feedback.
