### ISSUE TITLE
.NET 8 will be supported?

### ISSUE THREAD

**Issue by mendozagit** [mihirdilip/aspnetcore-authentication-apikey#39]

**Comment by mihirdilip** [comment]
@mendozagit 
yes, .NET 8 will be supported as soon as stable production release is available.

**Comment by mendozagit** [comment]
Great! Thanks

**Comment by paulirwin** [comment]
Hi @mihirdilip, .NET 8 is now fully released. Would you accept a PR for this change or would you rather do it yourself? Thanks!

**Comment by mihirdilip** [comment]
Hi @mendozagit & @paulirwin, new version with net8.0 supported has just been released on NuGet. Enjoy! :)

**Comment by mendozagit** [comment]
Thanks a lot @mihirdilip!
