### ISSUE TITLE
Provide sample application.

### ISSUE THREAD

**Issue by MNF** [mihirdilip/aspnetcore-authentication-apikey#5]
I really appreciate a very detailed documentation in readme.
However it will be useful to add an example folder with both client and server projects working together.

**Comment by mihirdilip** [comment]
Hi @MNF, I appreciate your suggestion.
I am working on another release with which I may include quick sample project within here on the repository.
But, here are some samples I already have on separate repositories.
- [authentication-serverside-samples](https://github.com/mihirdilip/authentication-serverside-samples)
- [authentication-clientside-samples](https://github.com/mihirdilip/authentication-clientside-samples)
   - The client side uses my other [restapi-client](https://github.com/mihirdilip/restapi-client) library which is still under development and preview is available on NuGet. 

I hope this helps you. If you are happy with this, please feel free to close the issue. :)
Let me know if you have any queries.

**Comment by MNF** [comment]
I created PR https://github.com/mihirdilip/aspnetcore-authentication-apikey/pull/6 to add links to readme

**Comment by mihirdilip** [comment]
@MNF,  I appreciate your effort but I am sorry I am not accepting any PR at the moment. Thank you for your understanding.
